// <auto-generated />
namespace ShopMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PendingChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PendingChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201502081326572_PendingChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
