// <auto-generated />
namespace ShopMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IncludeBasket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncludeBasket));
        
        string IMigrationMetadata.Id
        {
            get { return "201502052306017_IncludeBasket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
